### ISSUE TITLE
Should not print "disabled by script" its not informative.

### ISSUE THREAD

**Issue by notnotmelon** [notnotmelon/maraxsis#101]

**Comment by Fr-Dae** [comment]
no idea what cost this or how to bypass ?

**Comment by tburrows13** [comment]
> no idea what cost this or how to bypass ?

It’s caused by the mod setting active = false on the entity. It’s up to the mod to tell you why. In 2.0, the mod can change this very text, which is a helpful way of telling the player what is wrong :)

**Comment by Fr-Dae** [comment]
what should I do then?

**Comment by notnotmelon** [comment]
![image](https://github.com/user-attachments/assets/ca8f63c8-d65b-40d4-87a3-54b7770394c8)

**Comment by Fr-Dae** [comment]
- ✔ domes
- ✔ elec
- ✔ atmo
- ✔ light
- X foundry

i really don't understnd

**Comment by Fr-Dae** [comment]
https://youtu.be/WuTLJvmignI

**Comment by Fr-Dae** [comment]
https://youtu.be/issSJchpuBM

no idea why it's so laggy on OBS

**Comment by Fr-Dae** [comment]
- set temp  to 25°c
- if you have add atmo with unfine temp, uncraft it and place it again.
- always place the  infinit pipe at  one tiles from your destination, configure it THEN add a normal pipe.
