### ISSUE TITLE
[issue]pressure domes

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#103]
i have some trouble with the pressurid dome.
- right clic don't remove them, you need apply a other
- if you missplaced one it's hard to move
- if you missclic on the wrong place you remove one you have already placed
- hard to understand how to fit them
- issue with drag placement
![Capture d’écran du 2024-12-09 20-10-11](https://github.com/user-attachments/assets/67a7fb16-4be8-4898-bd12-59e5ab2ae8b6)
- any possibility to make it more trasnparent ?

**Comment by Fr-Dae** [comment]
why it's need poles if it's like space station floor ?

**Comment by Fr-Dae** [comment]
make blueprint it's ... broken

**Comment by notnotmelon** [comment]
Hi, please make separate issues for each problem so that they can be fixed one by one.

**Comment by Fr-Dae** [comment]
but it's all conserne the domes, i need spit too ?

**Comment by Fr-Dae** [comment]
@notnotmelon

**Comment by Fr-Dae** [comment]
https://youtu.be/WuTLJvmignI

**Comment by notnotmelon** [comment]
Thanks for splitting this. I will close the original.
