### ISSUE TITLE
[2024.12.10] [BUG]Conflict with [Quick Map Tag Teleport (0.1.1)]

### ISSUE THREAD

**Issue by qw21zxsa** [notnotmelon/maraxsis#107]
**Factorio & Maraxsis version number**
Factorio 2.0.23   Maraxsis1.21.9

**Describe the bug**
When I tried to dive into the trench on a submarine, an error occurred and it conflicted with mod [Quick Map Tag Teleport] (0.1.1)

**Screenshots**
![image](https://github.com/user-attachments/assets/da6eedd0-50e1-4b36-9f78-a65c23fdacdc)

**Save file & log**
模组「Maraxsis (1.21.9)」引发了无法恢复的错误。
请向模组作者反馈此错误。

Error while running event maraxsis::maraxsis-trench-submerge (ID 253)
模组「快速地图标签传送 [Quick Map Tag Teleport] (0.1.1)」引发了无法恢复的错误。
请向模组作者反馈此错误。

Error while running event QuickMapTagTeleport::script_raised_teleported (ID 90)
Entity is not character.
stack traceback:
	[C]: in function '__index'
	...__/scripts/event_handlers/custom_input_event_handler.lua:37: in function <...__/scripts/event_handlers/custom_input_event_handler.lua:36>
stack traceback:
	[C]: in function 'teleport'
	__maraxsis__/scripts/submarine.lua:152: in function 'decend_or_ascend'
	__maraxsis__/scripts/submarine.lua:183: in function <__maraxsis__/scripts/submarine.lua:177>

**Comment by notnotmelon** [comment]
Hi, Thanks for the report.

This seems to be a bug with the other mod. Can you make a report there?
