### ISSUE TITLE
[24.12.10] [FEAT]Improve domes placement

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#109]
- Factorio 2.0.24
- Mods 1.21.9
## probleme
the placement of the domes structure is really tricky.
- if you place it too close to another it cancels out the first.
- you can't remove a domes with a simple right click, 
https://youtu.be/oCp30-YyjOE

# idea
adding a red/green zone to facilitate alignment and correct placement would undoubtedly correct these problems.
and possibly the problem of placement by dragging. 

https://youtu.be/pTg2PXMS9x4

**Comment by Fr-Dae** [comment]
link to
https://github.com/notnotmelon/maraxsis/issues/103

**Comment by Fr-Dae** [comment]
and maybe to 
https://github.com/notnotmelon/maraxsis/issues/112

**Comment by tylercd100** [comment]
I also want to add on to this issue as it is related. When I "shift+click" to place a dome and there are rocks or other things that need to be deconstructed, the robots will clear the rubble but for some reason the dome item becomes destroyed and lost in the process. I dont know if this was patched recently.

**Comment by notnotmelon** [comment]
> I also want to add on to this issue as it is related. When I "shift+click" to place a dome and there are rocks or other things that need to be deconstructed, the robots will clear the rubble but for some reason the dome item becomes destroyed and lost in the process. I dont know if this was patched recently.

This one is now patched.
