### ISSUE TITLE
[24.12.10] [FEAT] make dome more transparent

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#110]
more easy to look on it  if the glass it's more transparent

**Comment by Andargor** [comment]
If there would be a way to hide the structural elements as well, it would make placement easier. The struts currently hide belts and other items.

**Comment by Fr-Dae** [comment]
other games have had a similar problem, the nicest solution I've seen is for the element to become transparent when the cursor is on it or next to the player, https://preview.redd.it/what-options-need-to-change-to-dont-see-the-semi-v0-ovvrkt8plawa1.png?width=1360&format=png&auto=webp&s=d860ca76e8ea612691179c5427770b4647a5ac3d

**Comment by hikeonpast** [comment]
In balancing QOL with planet-specific challenges, it's possible to leverage the day/night cycle to make it easier to view inside domes at night if they have a lamp installed.

**Comment by Frontrider** [comment]
I'd just make the beams that hold up the dome transparent. That works in any views, from anywhere.

**Comment by Fr-Dae** [comment]
![Capture d’écran du 2024-12-20 06-51-50](https://github.com/user-attachments/assets/66bebd8e-b07a-48c6-bcec-1cc9cf5ff303)
![Capture d’écran du 2024-12-20 06-51-08](https://github.com/user-attachments/assets/7a1726ff-7041-46f7-9e8d-c581039a737f)

adding image about this PR, for documetation

**Comment by Frontrider** [comment]
I was thinking more like this. The base of it must remain solid, because the place where the ground meets the sand is ugly.
![image](https://github.com/user-attachments/assets/40faf5f9-aaf6-4c7d-bd9f-c9f105705b3a)

**Comment by Frontrider** [comment]
I was thinking more like this, to still cover the edge of the flooring.
![dome](https://github.com/user-attachments/assets/361388ba-8681-4d29-857d-f3d7b56b4724)

May only work if you edit the model itself.

**Comment by Fr-Dae** [comment]
atm it's by trasnparent if your cursor are on it, pretty smart

**Comment by notnotmelon** [comment]
> I was thinking more like this, to still cover the edge of the flooring. ![dome](https://private-user-images.githubusercontent.com/6755034/397660958-361388ba-8681-4d29-857d-f3d7b56b4724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDAxMzgsIm5iZiI6MTczNDY5OTgzOCwicGF0aCI6Ii82NzU1MDM0LzM5NzY2MDk1OC0zNjEzODhiYS04NjgxLTRkMjktODU3ZC1mM2Q3YjU2YjQ3MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMTMwMzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkxODMxMjllNmM2NjY2OWZlMmE5OGExYzY2ODk1NmFkYmQzOTA3MDY5NGVhNDJlNDE5NzNmYzc0NWQzNWQ4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HZBO9PbNhUtMwAAlm_Z5b1x55hmeJmMI_XAosTv9Cms)
> 
> May only work if you edit the model itself.

Easier solution would be to implement tile transitions for the dome tiles. For this reason I will reopen this issue.
