### ISSUE TITLE
[24.12.10] [BUG] make blueprint with domes it's tricky and ungly

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#112]

**Comment by notnotmelon** [comment]
- Tricky how?
- Ugly how?

I need specific and workable suggestions.

**Comment by Fr-Dae** [comment]
as the dones are not currently a complete structure, if you make a blueprint, for example to use the placement function on the absolute grid, the blueprint will be ugly and unusable.
