### ISSUE TITLE
[24.12.10] [FEAT] make the placement of pit pipes more obvious or readible. 

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#113]
## yes, it's that little green thing you have to look for, good luck. 
![Capture d’écran du 2024-12-09 22-16-33](https://github.com/user-attachments/assets/9ecb522a-1226-4d7d-b26b-315e99943118)
![Capture d’écran du 2024-12-09 22-16-57](https://github.com/user-attachments/assets/2247229e-ebfd-4a9a-8f97-2835315597b4)

**Comment by notnotmelon** [comment]
Thanks for the issue. This was resolved in https://github.com/notnotmelon/maraxsis/commit/4d9e1a2f7b7a7453182cb8b132a77d358e448497
