### ISSUE TITLE
[24.12.10] [BUG] (feature ?) fish tower accepte seed ?

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#114]
FR ?

![Capture d’écran du 2024-12-09 22-37-56](https://github.com/user-attachments/assets/9a3e3e02-df7e-4cc7-bd41-e7a684d21079)

**Comment by notnotmelon** [comment]
Sorry, I can't fix this one. The mod API does not support filters here. But the truth is, with seeds it will never actually plant these.
