### ISSUE TITLE
Inconsistent Planet Icon

### ISSUE THREAD

**Issue by kryzeth** [notnotmelon/maraxsis#116]
**Factorio & Maraxsis version number**
Factorio v2.0.23, Maraxsis v1.22.0

**Describe the bug**
Maraxsis.png in /graphics/planet does not match maraxsis-hd.png or maraxsis-starmap-icon.png
The discrepancy is also noticeable in-game.

**To Reproduce**
1. Look at the planet icon in the Factoripedia
2. Compare it to the starmap planet icon
3. The hd icon might not even be in use?

**Expected behavior**
The planet icons should probably be consistent with each other?

**Screenshots**
![Image attached](https://imgur.com/jhjn5Yg.png)

**Comment by notnotmelon** [comment]
Also, the HD planet is active when the HD planets mod is installed.

**Comment by kryzeth** [comment]
I never noticed that... now I just have more questions than answers... Has nobody else noticed this? I know it's such a minor issue, but I can't imagine why they would be different, like how does this even happen...
