### ISSUE TITLE
[1.22.0] [BUG] Need a foundry to make glass, can't make it in hydro plant

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#117]
**Factorio & Maraxsis version number**
Please post both the Factorio and Maraxsis version numbers here.

Factorio 2.0.23
Maraxsis 1.22.0

**Describe the bug**
You need a foundry to make glass for a dome, but you can't place down a foundry without a dome. Or I am missing something?

**To Reproduce**
1. Try to make glass without a dome

**Expected behavior**
Ability to make glass without a dome

**Comment by notnotmelon** [comment]
Hello, thanks for the report. This is working as-intended. You can alternatively get glass from mining mollusk husks.

**Comment by Andargor** [comment]
> Hello, thanks for the report. This is working as-intended. You can alternatively get glass from mining mollusk husks.

Mollusk husks? Where are those?
