### ISSUE TITLE
[1.22.0] [FEAT] Allow bringing power from the top to the trench

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#118]
**Is your feature request related to a problem? Please describe.**
Can we bring power from the top layer into the trench? Or do we need to build salt reactors in the trench and there is no way to connect the top power generation into the trench? Can the trench ducts transmit power? If not can they?

**Describe the solution you'd like**
Transmit power to trench with wires or duct

**Describe alternatives you've considered**
Building a salt reactor in the trench, but that doesn't allow using top surface generation.

**Comment by Andargor** [comment]
> I've asked the same question. Here are a couple solutions to getting power to trench:
> 
> 1. Pipe steam into the trench (my fav)
> 2. Salt reactor in trench
> 3. Pump water into trench.   Use water in  heat exchanger with  rocket fuel excess or regular nuclear setup.
> 
> Already we have to pipe atmosphere, down and lava up. A steam pipe didn't appear to cumbersome.

Huh. How do you make the steam and how do you automate moving solids between topside and the trench? We can't get the construction subs to work.

**Comment by tylercd100** [comment]
@Andargor the only way to get items to the trench is to automate a Diesel Sub (i mentioned this in a different issue). It is much easier to use trench ducts to send fluids between the surfaces as it is less finicky.

To make steam, there is a rocket fuel recipe available to you by using Oxygen and Hydrogen, water can be crafted from the same but in a chemical plant. 

You will need a dome to use a nuclear reactor or a heating tower though

**Comment by Andargor** [comment]
As I mentioned elsewhere, we use fusion power, so it is very jarring to have to set up a nuclear reactor or heating towers (as we are doing atm). We have these nice tungsten ducts going into the trench, but can't pass wires? Dunno, seems a bit of an artificial hurdle.

**Comment by tylercd100** [comment]
When you say "We" are you including the people that choose to go to maraxsis first before aquilo? Aquilo is not a requirement to go to maraxsis.

**Comment by Andargor** [comment]
Sorry, it's a multiplayer game, "we" is the group :)

**Comment by tylercd100** [comment]
Oh my bad! Well that makes way more sense :)

**Comment by notnotmelon** [comment]
Thanks for the report and discussion. After some thought I've decided I will not add this. Here is why:

option A) Add this functionality to the trench duct.
- This makes the trench duct even more complicated. Both for the user and for the codebase.

option B) Add a new entity with this functionality.
- Early on in dev I considered adding fiber optics that would fill this niche.
However now I realize that this feature would not fit. Maraxsis already has more unique entities than any other planet.
This would be yet more graphics and code to maintain.

Additionally, it is a moving goalpost. If I add power connections, why not red and green circuits?

Adding power connections removes an important puzzle from maraxsis. On our server we have a nice setup that swaps between a steam trench duct and salt reactor for trench energy. As solar said, there are many options available to solve this problem.

The point about fusion energy: I think there is nothing preventing the use of fusion in the trench.
