### ISSUE TITLE
Missing a good way to transfer fluids to the trench. Currently you have to use barrels.

### ISSUE THREAD

**Issue by notnotmelon** [notnotmelon/maraxsis#12]

**Comment by tylercd100** [comment]
+1 

I cannot figure out how to unbarrel atmosphere in the trench without power generation and power generating machines do not work in the trench without atmosphere in the dome.

**Comment by tylercd100** [comment]
Maybe another option could be some sort of unique power generator for the trench like a "geo thermal heat exhanger" or "molten salt reactor".... still need to unbarrel water though for steam. Idk just putting it out there

**Comment by notnotmelon** [comment]
![image](https://github.com/user-attachments/assets/1d5de1f7-91e0-401e-8563-b5ffd17f1432)
