### ISSUE TITLE
[1.22.0] [BUG] Can't set waypoint for construction sub in the trench

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#122]
**Factorio & Maraxsis version number**
Factorio 2.0.23
Maraxsis 1.22.0

**Describe the bug**
Can't set waypoint for construction sub in the trench

**To Reproduce**
1. Select the waypoint tool
2. Right click in the trench

**Expected behavior**
A waypoint for the construction sub is set (I assume the sub will move from topside to the trench and back if there aew waypoints for it)

**Comment by tylercd100** [comment]
So I am not sure if this is a bug or not. 

It seems to me that construction subs should only be used for construction tasks (construct, deconstruct and upgrade) and the diesel sub is the one that you should use for automated schedules as you can set a waypoint in the trench by riding in it and manually submerging.

It is a little confusing though

@notnotmelon what are your thoughts here? is this intended behavior, a lack of communication or just an incomplete feature?

**Comment by tylercd100** [comment]
Okay I spoke too soon, 

With patch 1.22.0 you can successfully use submerge option in the schedule (you previously couldnt manually submerge while riding in a construction sub so you couldnt create the trench way points)

Okay so as it stands right now, the only way to make waypoints in the trench is to manually ride in the sub you want to automate, manually submerge, then create those waypoints in the trench

I agree this is cumbersome and it would be more intuitive if you could set waypoints while in remote view

**Comment by Andargor** [comment]
Maybe there should only be one type of sub for both types of tasks instead of two separate classes?

**Comment by tburrows13** [comment]
When a sub submerges, all spidertron/patrol remotes are disconnected, so you have to reconnected it by click-dragging, or get a new connected one from the sub's GUI (or Control+Shift+Q). Once you've done that, you can happily carry on placing waypoints in remote view. You can't place waypoints on a surface that the submarine is not currently occupying.

There was a bit of jank in the patrol renders not updating correctly during a submerge, that has now been fixed.
