### ISSUE TITLE
[1.22.1] [BUG] Landing pad is not in dome logistic network

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#124]
**Factorio & Maraxsis version number**
Factorio 2.0.23
Maraxsis 1.22.1

**Describe the bug**
Making logistic requests does not pull from the landing pad, even if it is within the logistic zone. Stuff needs to be belted out, which is cumbersome.

**To Reproduce**
1. Make a logistic request from a dome for stuff in the landing pad

**Expected behavior**
As in vanilla, the landing pad is in the logistic zone and can honor requests

**Comment by notnotmelon** [comment]
It works for me. It seems the edge of the logistic zone must intersect with the center of the cargo landing pad. Have you tried this?
I wonder if standard roboports do this. It might be a vanilla bug with how the cargo landing pad works.

**Comment by notnotmelon** [comment]
Thanks for the report. Based on the discussion from #127, I am going to close this.
