### ISSUE TITLE
[1.22.1] [BUG] Crash when modifying construction sub

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#125]
**Factorio & Maraxsis version number**

   0.021 Loading mod settings Constructron-Continued 2.0.14 (settings.lua)
   0.021 Loading mod settings FluidMustFlow 1.4.1 (settings.lua)
   0.021 Loading mod settings SpidertronEnhancements 1.10.6 (settings.lua)
   0.022 Loading mod settings SpidertronPatrols 2.5.5 (settings.lua)
   0.022 Loading mod settings maraxsis 1.22.1 (settings.lua)
   0.022 Loading mod settings maraxsis 1.22.1 (settings-updates.lua)
   0.025 Loading mod core 0.0.0 (data.lua)
   0.036 Loading mod base 2.0.23 (data.lua)
   0.155 Loading mod Constructron-Continued 2.0.14 (data.lua)
   0.163 Loading mod elevated-rails 2.0.23 (data.lua)
   0.182 Loading mod FluidMustFlow 1.4.1 (data.lua)
   0.189 Loading mod quality 2.0.23 (data.lua)
   0.198 Loading mod SpidertronEnhancements 1.10.6 (data.lua)
   0.203 Loading mod space-age 2.0.23 (data.lua)
   0.413 Loading mod aai-signal-transmission 0.5.0 (data.lua)
   0.426 Loading mod SpidertronPatrols 2.5.5 (data.lua)
   0.444 Loading mod maraxsis 1.22.1 (data.lua)
   0.485 Loading mod base 2.0.23 (data-updates.lua)
   0.496 Loading mod Constructron-Continued 2.0.14 (data-updates.lua)
   0.505 Loading mod quality 2.0.23 (data-updates.lua)
   0.520 Loading mod SpidertronEnhancements 1.10.6 (data-updates.lua)
   0.532 Loading mod space-age 2.0.23 (data-updates.lua)
   0.546 Loading mod SpidertronPatrols 2.5.5 (data-updates.lua)
   0.556 Loading mod maraxsis 1.22.1 (data-updates.lua)
   0.567 Loading mod Constructron-Continued 2.0.14 (data-final-fixes.lua)
   0.577 Loading mod SpidertronEnhancements 1.10.6 (data-final-fixes.lua)
   0.590 Loading mod SpidertronPatrols 2.5.5 (data-final-fixes.lua)
   0.601 Loading mod maraxsis 1.22.1 (data-final-fixes.lua)

**Describe the bug**
Set up a construction bot with a logistic group to pull fuel from the network and trash barrels, then a fission power pack, battery and roboport. The logistic group got overwritten with a request for construction bots. Tried to change it back to fuel, game crashed.

**To Reproduce**
1. Set up construction bot with "Submarine Fuel" logistic group, request 100 light oil barrel, set barrel to trash (all qualities, 0 quantity) EDIT: the default unnamed group was deleted first, so that "Submarine Fuel" is the only group remaining, might be the cause
2. Install fission power plant, battery Mk3, roboport
3. Logistic group should change automatically by script
4. Change it back, crash

**Expected behavior**
No crash, no logistic group overwritten

**Screenshots**
https://i.imgur.com/2ASni0Y.png

**Comment by notnotmelon** [comment]
Thanks for the report. However this crash will not be fixed.

Here is why: https://github.com/notnotmelon/maraxsis/issues/90
