### ISSUE TITLE
[1.22.1] [FEAT] Better handling of multiple qualities of hydro science

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#126]
**Is your feature request related to a problem? Please describe.**
Currently hydro science comes out with multiple qualities, which is a real pain to automate on rockets since you can only do partial launches unless you have 1000 of every quality before you launch.

Maybe allow to turn off quality on science packs, without having to resort to easy mode?

**Describe the solution you'd like**
Easy logistics on the science packs. Maybe have a recipe to convert lower quality science to better quality science? For example, allow making 2 normals into 1 uncommon, etc. so there can be a solution to convert all of them to legendary-equivalent, with some loss depending on which problem we want to resolve (logistic headache or efficiency)

**Describe alternatives you've considered**
Partial launches with a request for each quality type.

**Comment by notnotmelon** [comment]
This is resolved as of https://github.com/notnotmelon/maraxsis/commit/03c9325147cd8b465483ea23efd8b3951597939e

It's now possible to completely disable quality on a hydro plant by mixing speed beacons and speed conduits.

**Comment by Andargor** [comment]
What is a speed conduit?

**Comment by tylercd100** [comment]
A new type of beacon that can be placed on the sea floor without a dome, it allows speed, eff, and quality modules and has 4 slots. 

since speed modules reduce quality, you can use these new beacons to reduce the quality to 0%
