### ISSUE TITLE
[1.22.1] [FEAT] Allow rocket silo to be on the dome network for logistic requests

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#127]
**Is your feature request related to a problem? Please describe.**
The rocket silo is not on the logistic network, which means you can't automate launches, science packs need to be loaded by hand.

**Describe the solution you'd like**
As in vanilla, the rocket silo should pull logistic requests in automatic mode when within a dome logistic zone

**Describe alternatives you've considered**
Loading manually...

**Comment by notnotmelon** [comment]
![image](https://github.com/user-attachments/assets/8940c31a-0594-4d22-a672-6c899af5745e)

**Comment by Andargor** [comment]
I`m using the same image that in my landing pad post, the rocket silo is fully within the orange zone: https://i.imgur.com/Y87ggmG.jpeg

**Comment by notnotmelon** [comment]
I have no idea what's causing this. Can you send your save?

**Comment by Andargor** [comment]
I think the top dome is bugged. I tried replacing it with another dome with a different quality and I get a "pressure dome is in the way" message. is it intended that you cannot upgrade the domes? https://i.imgur.com/5OvFES2.jpeg

In any case, while I was holding the new dome ghost, the logistic connections between domes appeared.

Is there a way to send you files outside of github? I am concerned about private information that may or may not be in the save.

**Comment by tylercd100** [comment]
notnotmelon can be reached in the community discord https://discord.gg/xRYEZYz5WR

**Comment by Andargor** [comment]
> notnotmelon can be reached in the community discord https://discord.gg/xRYEZYz5WR
> 
> You could send a private message to him there

The save file is 65MB compressed, too large for Discord. I'll have to go through the uncompressed JSON to see if there's anything private in there before posting.

**Comment by Andargor** [comment]
Link to save sent to @notnotmelon on Discord

**Comment by Andargor** [comment]
I tested in single player and picking up and putting down the silo seems to fix it. The top dome is buggy, but if I apply a different dome on it, seems to fix the launch pad issue as well. Trying in multiplayer

**Comment by Andargor** [comment]
I did this: pick up and set down silo, and then try to apply a normal dome on top of the uncommon one at top. Fixed both this issue and https://github.com/notnotmelon/maraxsis/issues/124

**Comment by dakkhuza** [comment]
Stopgap solution: If you load the science packs into the rocket silo with inserters it should automatically launch when full if there's a platform requesting the items loaded into it

**Comment by Andargor** [comment]
> Stopgap solution: If you load the science packs into the rocket silo with inserters it should automatically launch when full if there's a platform requesting the items loaded into it

Interesting. It still causes an issue with the "All Requests Completed" wait condition though. I guess we could use timers.

**Comment by notnotmelon** [comment]
Thanks for the report and save. I now believe that this was an issue with increasing the roboport area in an update. Mining and rebuilding the roboport/silo seems to resolve it. Since this issue will not effect new users, I am going to mark this as closed.
