### ISSUE TITLE
Submarines are destroyed when they attempt to rise up from trench into unrendered surface terrain[1.23.4] [BUG]

### ISSUE THREAD

**Issue by nicholasgower** [notnotmelon/maraxsis#133]
**Factorio & Maraxsis version number**
Factorio 2.0.23
Maraxis 1.23.4

**Describe the bug**
While riding a submarine in a trench, returning to the surface will destroy the submarine if the surface directly above the submarine has not been generated yet.

**To Reproduce**
1. Enter a Diesel submarine as a player on the surface of Maraxsis. Go to a trench that is surrounded by ungenerated terrain. Descend down the trench.
2. Once in the trench, move your submarine into an area where the corresponding surface chunks have not generated yet.
3. Attempt to return to the surface.
**Expected behavior**
The expected behavior is for the player and submarine to resurface from the trench, generating the surrounding terrain if it has not been generated yet.

**Save file & log**
My save file is too big to upload to Github, but given how I've barely scratched the surface of this mod, I don't see how supplying it will assist you.
[factorio-current.log](https://github.com/user-attachments/files/18104387/factorio-current.log)

**Comment by notnotmelon** [comment]
I can't reproduce this. I went a few km out and submerged yet the submarine was still there.

![image](https://github.com/user-attachments/assets/96df4695-6820-46d6-bc50-23335b90d274)

Is it possible that you used the smoke bomb keybind from spidertron enhancements?

https://github.com/tburrows13/SpidertronEnhancements/raw/master/resources/quick-toggle.gif

**Comment by notnotmelon** [comment]
It has been 24 hours. I'm going to mark this as stale. If you experience this bug again, please create a new ticket with a link to this one.
