### ISSUE TITLE
[1.23.29] [FEAT] Reduce Abyssal Gear to 2x2

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#140]
**Is your feature request related to a problem? Please describe.**
Currently Abyssal Gear is 3x3 which is a really awkward size, since most things that are larger than 1 on both sides are multiples of 2

**Describe the solution you'd like**
2x2 Abyssal Gear

**Comment by notnotmelon** [comment]
Is it that bad? You can always pad it with battery, toolbelt, or belt immunity equipment.
Additionally, diving gear stacks so using a 2x2 grid allows for an even size.

**Comment by Andargor** [comment]
It is very inconvenient since the abyssal gear can only be used on Maraxsis. Whenever you go to or from Maraxsis, you need to juggle your loadout a fair amount since things don't fit neatly, and when you go back you have to get into a sub (to avoid drowning) and refit your loadout.

If it were 2x2, you would just leave it in and sacrifice a shield, or a PDL and not think about it. Otherwise it's such a hassle than players might just forgo using it at all and just use subs when they visit Maraxsis.

Permit me to ask you the reverse question, is it so bad and unbalanced to have it 2x2?
