### ISSUE TITLE
[1.23.29] [FEAT] Allow bidirectional fluid passthrough connections in Hydro Plant

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#141]
**Is your feature request related to a problem? Please describe.**
Allow fluid connections on the hydro plant to be bidirectional and allow pass-through.

**Describe the solution you'd like**
Being able to chain Hydro Plants.

**Comment by notnotmelon** [comment]
Thanks for the suggestion. I cannot add this. Bidirectional fluid connections mean that there is a shared fluidbox between both the input and the output. However some recipes in the hydro plant have two fluid inputs or two fluid outputs. For example the EM plant always has only 1 fluid input.
