### ISSUE TITLE
Can someone show me a configuration with beacons and conduits that reduces quality bonus to 0%?

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#145]
In https://github.com/notnotmelon/maraxsis/issues/126 I was told that the quality bonus of the hydro plant can be reduced to 0% using beacons with speed modules and the new conduits with speed modules. This is in order to simplify our build.

We have not been able to do so, we only got it down to +18%. Can someone show me a +0% setup?

**Comment by Andargor** [comment]
Also maybe the negative effect of speed modules on quality should not be affected by neighboring conduits?

**Comment by notnotmelon** [comment]
Here is such a setup:

![image](https://github.com/user-attachments/assets/000fe16a-d185-4d83-9542-2ce31e04d9d5)

As you can see, 8 legendary beacons combined with 6 legendary conduits are enough to reduce the quality to 0.
This setup does require legendary items however its possible to roll quality conduits in the hydro plant, making this process quite straightforward.

For example, here is my conduit gamba:

![image](https://github.com/user-attachments/assets/1219d9f4-6d9b-405f-9061-55753820a033)

**Comment by notnotmelon** [comment]
You may also build this setup if legendary beacons are too expensive:

![image](https://github.com/user-attachments/assets/b7396236-dd02-4494-8dd9-59623fc36a64)
