### ISSUE TITLE
[00.00.00] [BUG] Switching submarine from manual to auto throws an error

### ISSUE THREAD

**Issue by hikeonpast** [notnotmelon/maraxsis#151]
**Factorio & Maraxsis version number**
Factorio 2.0.23 win64
Maraxsis 1.23.43

**Describe the bug**
Switching a submarine manual to auto with an empty waypoint list throws an error:

Error while running event SpidertronPatrols::on_spider_command_completed (ID 181)
__SpidertronPatrols__/scripts/spidertron-control.lua:230: attempt to index local 'waypoint' (a nil value)
stack traceback:
	__SpidertronPatrols__/scripts/spidertron-control.lua:230: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

**To Reproduce**
1) build a new submarine
2) switch it from Manual to Auto without adding any waypoints

**Comment by notnotmelon** [comment]
Thanks for the report. This is an upstream issue with spidertron patrols. I've raised the issue with that mod.

**Comment by tburrows13** [comment]
Fixed in Spidertron Patrols 2.5.8 :)
