### ISSUE TITLE
[00.00.00] [FEAT] small one: the submarine icons on the map view should mirror  in the direction of sub travel

### ISSUE THREAD

**Issue by hikeonpast** [notnotmelon/maraxsis#153]
**Is your feature request related to a problem? Please describe.**
The sub icons on map view always have the sub facing toward the right.  It looks a little funky when the sub is travelling left but facing right.

**Describe the solution you'd like**
Even if just left/right mirrored, it would be cool to have the sub icon pointed in roughly the direction of travel.

![image](https://github.com/user-attachments/assets/311cfcf9-cf16-4abe-93f9-fb8745eafcfe)

**Comment by notnotmelon** [comment]
Thanks for the suggestion. I agree this would be quite a nice feature, however it's not possible with the current modding API.
The map has no support for luarendering. If this functionality is ever added then I will reopen this ticket.
