### ISSUE TITLE
[00.00.00] [BUG] Trench Exploration "Tips and Tricks" has a broken path

### ISSUE THREAD

**Issue by hikeonpast** [notnotmelon/maraxsis#154]
**Factorio & Maraxsis version number**
Factorio 2.0.23 win64
Maraxsis 1.23.43

![image](https://github.com/user-attachments/assets/689e79a9-ede2-4bfd-8414-6996acceadd0)

**Comment by Fr-Dae** [comment]
the [00.00.00] should be the date in iso 8601 format in title

**Comment by notnotmelon** [comment]
Thanks for the report. It's fixed in the latest version.

**Comment by notnotmelon** [comment]
Ref: https://github.com/notnotmelon/maraxsis/issues/87
