### ISSUE TITLE
[2024-12-15] [FEAT] Running low on power can cause a chain reaction that can not be recovered from without outside help.

### ISSUE THREAD

**Issue by Frontrider** [notnotmelon/maraxsis#155]
**Is your feature request related to a problem? Please describe.**
IF the base ever dips in power then it can slow down salt production just enough to cause a power death spiral that you may not notice until you have a complete blackout.
It also completely breaks the salt loop, because now you can't clean your existing filters anymore, because you can't make brackish water for the electrolysis that you need to make clean water.

**Describe the solution you'd like**
I don't know. That self sustaining loop is fundamental to the mod but I don't know how to recover from it if/when it breaks down.

On a sizeable base it can't be reclaimed without either building a second base to make the salt (not connected to the same power network) which is also a second problem as it needs to make enough salt to supply you, or shipping in a secondary source to replace the salt reactors with (not supplement, because on that spot you won't think of using them anymore)

That is either solar, normal nuclear, or fusion.

An alternative source of water that is not making it from this loop may help, as that lets you clean your filters, so you can reboot it with power alone, instead of manually throwing the dirty filters into chests and feeding the machines with fresh filters. IF you are lucky enough it may let you buffer enough water for the cycle to restart itself.

**Describe alternatives you've considered**
I'm shipping in a billion solar panels and accumulators, as those never betrayed me. Salt reactor at lest gets replaced with a pair of recyclers to improve stability.

**Additional context**

**Comment by Frontrider** [comment]
The final solution was to import water from nauvis so I can clean my filters. After that the factory rebooted.

**Comment by Fr-Dae** [comment]
the [00.00.00] should be the date in iso 8601 format in title

**Comment by notnotmelon** [comment]
Personally I do not feel there is a problem here. Recovering from blackouts has always been a key feature of factorio, and especially now on aquilo there is even more precedent in vanilla.

Additionally, I believe the straightforward solution for this problem is heating towers with rocket fuel. Rocket fuel is abundant on maraxsis and can be buffered.

Compared to aquilo, we have significantly stronger solar panels.
I don't think maraxsis is designed for only use of only 1 power source, it's okay to have a mixture.

**Comment by Frontrider** [comment]
Different approach then: what if the salt reactor was pushed back a bit, so it does not look like the default option for power. Salt is a local resource, that makes the player inclined to use it "as intended", like burning spoilage and rocket fuel on Gleba.

The difficulty curve on it is good, but pushing it back might be closer to the real fix, as it forces me to have something more substantial than a handful of solar panels that I used to kickstart the operation before setting up something more unstable.

Maybe make it unlock with the hydro science alone like the sealant? A little CBT from dealing with the quality salts for the science to unlock a solution is probably reasonable. Maybe even tune it towards being a "compact reactor" for spacecraft or the trench as it's role? It was serving me really well down in the trench, and is one of the best choices down there imo.

**Comment by notnotmelon** [comment]
The problem with pushing it back is that this creates a psuedo-softlock to generate initial power in the trench.
The only solution to generating initial energy would be:

- Pump atmosphere to a dome inside the trench.
- Somehow generate steam on maraxsis surface.
- Pump steam into steam turbines which are inside that dome.

These three steps are not at all obvious, and currently there is no hard requirement on having any domes at all down there.
Breaking the psuedo-softlock feels more like a goose chase than intended gameplay.

On the other hand, the current solution is simple

- Place salt reactor
- Feed salt reactor

**Comment by notnotmelon** [comment]
I'm going to mark this one as not-a-bug for the above mentioned reasons.

**Comment by Frontrider** [comment]
Keep it in the back of your head anyways. The real issue might be the unstable output you get from the reactors. I *think* the problems really kicked in when I started to extract more rare salts from the belt to make science.

**Comment by notnotmelon** [comment]
Perhaps the solution is to allow read via circuit network of the internal buffer.

**Comment by Frontrider** [comment]
Perhaps. The issue unironically became one of the design principles of the machine. Not getting enough quality salt made it produce less power, as if I suddenly deconstructed some of my reactors. At lest that is what the fluctuation it produced looked like.

Maybe make it not consume salt when the buffer will not be able to take anything else in? So it can kinda self-regulate by simply eating more lower quality salt to produce the same power?
You could have an issue with quality salts backing up as you feed it (as it is not eating it at the same rate), but the solution is already there. You can opt to make less quality salt by using a chemplant.
