### ISSUE TITLE
[24.1215] [BUG]Fluid

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#158]
check this bug https://github.com/Klonan/KS_Power/issues/16

**Comment by notnotmelon** [comment]
Thanks for the report. I believe this is an issue with KS power & tiberium dawn. Hopefully it can be resolved on their side.

**Comment by Fr-Dae** [comment]
why fluid from ks and tiberium could modify yours ?

**Comment by notnotmelon** [comment]
Those are not my fluids.
