### ISSUE TITLE
[00.00.00] [BUG]

### ISSUE THREAD

**Issue by James-Fire** [notnotmelon/maraxsis#159]
**Factorio & Maraxsis version number**
2.0.25 and 1.23.29

**Describe the bug**
Maraxsis applies collision_masks to entities without first checking if they have collision.

My mod, https://mods.factorio.com/mod/James-Train-Mod, uses hidden accumulators with no collision under rails to store energy. Their collision is currently {layers={}, not_colliding_with_itself=true}. Looking at your code, it *should* leave them alone if the collision_mask was set to nil, like so

Accumulator.collision_mask = nil

Which I did try, but your mod was still adding the mask to it.

This is a problem because it makes my rails unable to have splits, like in the attached screenshot.

**To Reproduce**
1. Load both our mods.
2. Try placing a split using my Powered Rails.

**Expected behavior**
Check if entities have collision before adding masks to them.

**Screenshots**
![image](https://github.com/user-attachments/assets/f49dc783-e9de-4f40-a5b6-2cee3d27d6c9)

**Comment by notnotmelon** [comment]
Thanks for the report. I recommend you to update the version of maraxsis. This issue should be resolved.
