### ISSUE TITLE
[24.12.15][BUG]belt on water

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#161]
**Factorio & Maraxsis version number**
Please post both the Factorio and Maraxsis version numbers here.
- Factorio 2.0.25
- Mods 1.23.46

on nauvis many objet can be placed on water, like belt, underground belt, rail
it's shouldend

**Comment by notnotmelon** [comment]
Thanks for the report. This appears to be fixed as of 1.24.1
