### ISSUE TITLE
Fish in the subsurface in "build beneath your base" mod

### ISSUE THREAD

**Issue by M4nsy** [notnotmelon/maraxsis#163]
**Factorio & Maraxsis version number**
Factorio: 2.0.23 & Maraxsis: 1.23.52 
**Describe the bug**
found swimming fish from maraxsis in the subsurface of nauvis
i haven't found any note about compatibility issue with build beneath your base mod so i installed it with maraxsis i haven't been to maraxsis yet but when i dug to the subsurface i found maraxsis fish swimming in the dark and i can mine them if i reach them
![image](https://github.com/user-attachments/assets/4fd73efc-c959-4812-8d6f-bbff0d51947f)

**Save file & log**

Attach your save file and `factorio-current.log` file.
[Modded Playthro.zip](https://github.com/user-attachments/files/18153697/Modded.Playthro.zip)
[factorio-current.log](https://github.com/user-attachments/files/18153790/factorio-current.log)

**Comment by notnotmelon** [comment]
Thanks for the report. Can you cross-post this on the subsurface modpage? I believe its an issue with how that mod handles worldgen.
