### ISSUE TITLE
Mod requires experimental version of Space Age (2.0.26) when newest stable version is 2.0.23

### ISSUE THREAD

**Issue by delt1us** [notnotmelon/maraxsis#169]
**Factorio & Maraxsis version number**
Factorio Version: 2.0.23
Maraxsis Version: 1.24.6

**Describe the bug**
Maraxsis requires space age 2.0.26 but the latest stable version is 2.0.23. This results in the mod being unplayable unless you are on the beta branch of the game on steam as the game will give you a dependency error on launch. 

**To Reproduce**
1. Check steam beta participation to be on factorio stable
2. Install Maraxsis
3. Try to open Factorio
4. Get dependency error

**Expected behavior**
Maraxsis should require space age 2.0.23 so players on stable branch can play it.

**Screenshots**
Maraxsis dependencies:
![image](https://github.com/user-attachments/assets/1e008201-5499-48cd-b9f3-88dba993a34e)
Space age mod:
![image](https://github.com/user-attachments/assets/43ca7d41-81c0-4536-a243-a52d42fa0e04)
Version: 
![image](https://github.com/user-attachments/assets/e86ecefa-d4e0-4faf-a6c1-de7855c0c7d2)
Error: 
![image](https://github.com/user-attachments/assets/51a33c11-df6b-4356-b507-8409cfa1c4fd)

**Additional context**
Maybe this is intended but it will crash anyone's game who isn't on experimental branch.

**Save file & log**
Attach your save file and `factorio-current.log` file.
[factorio-current.log](https://github.com/user-attachments/files/18177229/factorio-current.log)

**Comment by delt1us** [comment]
Tested it out in a fork, it seems changing the required version to 2.0.23 in info.json is all that is needed to fix this, loaded my save file with no issues. 
https://github.com/notnotmelon/maraxsis/compare/main...delt1us:maraxsis:main

**Comment by Spacedestructor** [comment]
> Tested it out in a fork, it seems changing the required version to 2.0.23 in info.json is all that is needed to fix this, loaded my save file with no issues.
> [main...delt1us:maraxsis:main](https://github.com/notnotmelon/maraxsis/compare/main...delt1us:maraxsis:main)

thats what the info.json is for, it requires meta information such as the Displayed name, the internel name, the dependencies etc. so changing the number listed under dependencies will tell the game to expect something else. a similar trick used on "factorio_version" for example can allow you to run mods which dont need any changes to function but havent had there info.json updated yet.
Saw this threat because im experiencing the same bug and updating the info.json was also my first intuition assuming it doesnt actually need anything added in the experimental factorio branch.

**Comment by Semenar** [comment]
As far as I am aware, there was a change in base Factorio API in the 2.0.26 version. You will need to either update to experimental or use an older version of Maraxsis to play the mod.

**Comment by Spacedestructor** [comment]
> As far as I am aware, there was a change in base Factorio API in the 2.0.26 version. You will need to either update to experimental or use an older version of Maraxsis to play the mod.

the changelog on the forum says that they have added "minable flag" to deprecate "minable" as well as adding "is_updatable", "disabled_by_script", "disabled_by_control_behavior", "disabled_by_recipe", "is_freezable" and "frozen" to LuaEntity.

so the api changes are only relevant if the mod interacts with any of these but i havent checked the mods code so i dont know if this matters or not.

**Comment by Semenar** [comment]
> the changelog on the forum says that they have added "minable flag" to deprecate "minable" as well as adding "is_updatable", "disabled_by_script", "disabled_by_control_behavior", "disabled_by_recipe", "is_freezable" and "frozen" to LuaEntity.
> 
> so the api changes are only relevant if the mod interacts with any of these but i havent checked the mods code so i dont know if this matters or not.

As you can see from https://github.com/notnotmelon/maraxsis/commit/9ebee3051eaa49582be3fdeb21db1a364c5c4277, the problem is indeed with "minable".

**Comment by Spacedestructor** [comment]
> > the changelog on the forum says that they have added "minable flag" to deprecate "minable" as well as adding "is_updatable", "disabled_by_script", "disabled_by_control_behavior", "disabled_by_recipe", "is_freezable" and "frozen" to LuaEntity.
> > so the api changes are only relevant if the mod interacts with any of these but i havent checked the mods code so i dont know if this matters or not.
> 
> As you can see from [9ebee30](https://github.com/notnotmelon/maraxsis/commit/9ebee3051eaa49582be3fdeb21db1a364c5c4277), the problem is indeed with "minable".

so for us who are not on the experimental branch of factorio we are fine, the mod will continue to work even if we manually modify the version of the DLC in the dependencies.

**Comment by delt1us** [comment]
Given how lua works I doubt it would break anything if you manually change it to 2.0.23 until 2.0.26 is updated to stable, you probably just wont be able to mine the cliffs. It's probably fine to just update to experimental though, I just don't like doing that because going back to stable can delete all your blueprints.
I guess this is an intentional thing and not an oversight as I suspected.

**Comment by Spacedestructor** [comment]
> Given how lua works I doubt it would break anything if you manually change it to 2.0.23 until 2.0.26 is updated to stable, you probably just wont be able to mine the cliffs. It's probably fine to just update to experimental though, I just don't like doing that because going back to stable can delete all your blueprints. I guess this is an intentional thing and not an oversight as I suspected.

i have unziped the folder in the mods zip and given it a new mod version number so once stable gets updated the game will automatically see that the copy of the mod isnt valid anymore and should switch to using the zipped version which is unmodified.
in moments like these im glad factorio suppots the choice between mod versions if you have multiple versions of the same mod installed.

**Comment by notnotmelon** [comment]
Hi, sorry for the inconvenience. This mod will not function in versions below 2.0.26 due to various changes made to the modding API.
Expect frequent crashes for those editing the info json.
