### ISSUE TITLE
Steam is still on 2.0.23 so you have prevented all steam users from playing.

### ISSUE THREAD

**Issue by mindcloud69** [notnotmelon/maraxsis#172]
**Factorio & Maraxsis version number**
2.0.23 any new build since the 2.0.26 requirement went in place.

**Describe the bug**
Steam users can't play your mod on the release version.

**Comment by SHADOW-XIII** [comment]
you can switch to experimental version on Steam
or download older version of the mod from here and put it into factorio mods folder manually

that said, I think @notnotmelon could upload multiple versions to factorio mods portal, one for 2.0.23 and one for 2.0.26+

**Comment by tburrows13** [comment]
Your game won't update to versions that require an incompatible version of base game, so players on stable should be fine. There was a minor oversight though, so some players _may_ have accidentally got invalid versions earlier today. They can now just delete those, re-download the mod in game, and they'll get the correct version.

**Comment by mindcloud69** [comment]
Just to point out that today I went to update and an update to an incompatible version was offered.

![image](https://github.com/user-attachments/assets/146eb1a7-cd15-4354-9982-b37ead5385b4)

**Comment by tburrows13** [comment]
2.0.28 is now stable. Are you sure you aren’t on it?
