### ISSUE TITLE
Maraxsis breaks Factory Planner smelting Machine list

### ISSUE THREAD

**Issue by Hi-ImKyle** [notnotmelon/maraxsis#175]
**Factorio & Maraxsis version number**
2.0.27, 1.24.19

**Describe the bug**
Having Maraxsis installed breaks Factory Planner's Machine list. The Machine list is meant to display all the machines that can craft a specific recipe, but with Maraxsis installed, it seems to limit it to the Electric Furnace for smelting, see screenshots. The factory planner shows all machines, regardless of progress, so I am currently putting blame on Maraxsis as this only seems to show up with it enabled.

**To Reproduce**
1. Install Factory Planner & Maraxsis
2. Start a new game
3. Open Factory Planner in the top left
4. Click green plus button and add iron plates, set amount to anything, 60 is fine
5. In the products, click the iron plates and then the iron plate recipe
6. In the "Machine" column, right click the Electric Furnace, edit and try to change the machine from the Electric Furnace.
7. Should only give you the option of the Electric Furnace, no other machines.

**Expected behavior**
For all machines to be visible for smelting operations, stone, steel and electric, not just electric.

**Screenshots**
With Maraxsis
![image](https://github.com/user-attachments/assets/ef758b2b-dae2-4ae1-9600-f6ac661c29cd)

Without
![image](https://github.com/user-attachments/assets/c4b9c18e-a39a-42f3-b615-7138a6c10c93)

**Additional context**
It's not the end of the world to use a website for ratios instead of FP, so I'd consider this a pretty low priority bug :)

**Save file & log**
n/a

**Comment by notnotmelon** [comment]
And which district did you choose for this factory? Because stone and steel furnaces cannot be built on maraxsis.

**Comment by notnotmelon** [comment]
Thanks for the report. I've raised this in the factory planner github. https://github.com/ClaudeMetz/FactoryPlanner/issues/456
