### ISSUE TITLE
Idea from community

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#176]
- https://mods.factorio.com/mod/no-maraxsis-gatekeep-promethium
- https://mods.factorio.com/mod/beacon_maraxsis_tenebris

maybe consider add this stuff at optionnal settings ?
what do you think @notnotmelon

**Comment by notnotmelon** [comment]
What's the benefit of it? People could already install those mods. No need to make a setting when its so easy to install those mods.

**Comment by Fr-Dae** [comment]
have one official mod and no need dependency, and if many people take the second mod, it's maybe because it's usefull or needed ? =)
