### ISSUE TITLE
Bug or feature ? : map generation

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#179]
- Factorio 2.0.27
- Maraxsis 1.24.21

i don't know if it's a feature or a bug, but the center of area (near 0,0) it's almost empty of ressources

just unlucky ?

![Capture d’écran du 2024-12-20 06-48-21](https://github.com/user-attachments/assets/ce83c8ea-ec70-4d0b-a9ab-e3e5eb226f7e)

**Comment by Semenar** [comment]
I assume corals don't spawn on high elevation tiles, so it is not a bug.

As you can see, they are all near trenches.
