### ISSUE TITLE
Drowning despite being in the submarine

### ISSUE THREAD

**Issue by tylercd100** [notnotmelon/maraxsis#30]
My engineer continues to drown despite being inside the submarine with fuel. I get the on screen notifications warning me that i am drowning whilebpiloting the sub

I am playing on the steam deck, and noticed that the controller keybinding to enter/exit a vehicle is the same as diving down to the trench. I am not sure if this is related? But this is why i bring it up: Sometimes when i try to enter the sub it gets "confused", ill try to move in a direction and my engineer will pop out of the sub sometimes.

My hunch is that something about entering the sub is not setting the "state" correctly and the game thinks i am not actually in it despite being able to pilot

**Comment by notnotmelon** [comment]
Hi, I have made some changes to the mod in this area very recently. Can you tell me what version you experienced these issues in?

**Comment by tylercd100** [comment]
Yeah of course!

1.17.0

Some more feedback:
I have been playing for the past hour in the submarine and i havent had an issue, but once i switched to remote view for a little bit i got the drowning notification again. 

Loving the mod so far though, very nice work

**Comment by notnotmelon** [comment]
The remote view drowning was fixed in 1.17.3 👍

**Comment by tylercd100** [comment]
Updating to the latest version has resolved all my issues thank you
