### ISSUE TITLE
Solar power soft lock fix is not functioning?

### ISSUE THREAD

**Issue by tylercd100** [notnotmelon/maraxsis#32]
Hello again i hope you are not getting sick of me posting more work for you. Haha :)

Thank you for the solar power tweak for trenches, however there still seems to be an issue. I have placed 550 solar panels which is 600W x 550panels = 330KW
My one and only chemical plant has 3 x efficiency module mk3
Which reduces its power usage to between 7KW to 42KW. And it still says no power :-/

![17332847820906620471007018222866](https://github.com/user-attachments/assets/f83a74b7-5275-4631-80e7-999956d9b699)
![17332848395773088576547950884267](https://github.com/user-attachments/assets/070db73e-710d-4b3e-92c7-61f2c4688283)
![17332848912133039361726077954647](https://github.com/user-attachments/assets/85d4bf6f-bccb-4104-ac50-5d044defdd0f)

**Comment by tylercd100** [comment]
Version 1.18.4

**Comment by notnotmelon** [comment]
Thanks for the report. I will add a molten salt reactor for the trench.

**Comment by notnotmelon** [comment]
I sorta forgot that its always night in the trench.

**Comment by tylercd100** [comment]
Well i am excited to see what you come up with 😀

**Comment by notnotmelon** [comment]
![image](https://github.com/user-attachments/assets/84f8d915-2dcb-4a71-92f9-a52765ab0ab6)

**Comment by tylercd100** [comment]
Woohoo!!!

**Comment by tylercd100** [comment]
I am having issues unlocking it. I mine a chimney vent and it won't unlock :/
