### ISSUE TITLE
incompatibility problem with Renai transportation mod

### ISSUE THREAD

**Issue by Maxoxpower** [notnotmelon/maraxsis#35]
Renai transportation use hatch, tools that you can put "on" a building to throw things with insterter and another one who throw things from the building
.
Problem :   i cannot  put on a building anymore with maraxsis enabled. 

see here 

https://discord.com/channels/1260754935952314418/1277012731324665856/1313692492687872020

**Comment by Maxoxpower** [comment]
not all building after all got this problem. 

but at least assembly and furnace.

**Comment by eirshy** [comment]
Add nuclear reactors to the ones you can't use the hatch on.
Weirdly it doesn't break the Ejector Hatch.
