### ISSUE TITLE
[1.19.0] Turn off quality on hydro plants?

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#37]
We may be missing something, but our production keeps getting clogged because quality items are being produced and they need to be removed by hand. We have no storage options and the recycler cannot be installed without a dome (which we are trying to work towards, very slowly).

Is it possible to turn off the quality bonus on hydro plants?

**Comment by notnotmelon** [comment]
Yes, its possible to disable this with speed modules and speed beacons.

**Comment by Andargor** [comment]
Ok, but before you get a dome power is very limited (solar only, no accumulators) and we are struggling to produce 1000 glass because we manually empty the hydro plants of quality items that block them. Is this supposed to be the challenge? So far it has proven very tedious, no offense.

**Comment by notnotmelon** [comment]
I have released a patch that makes it 500 glass instead of 1000. Should help.

**Comment by notnotmelon** [comment]
And finally, I have just added a new easy to easily void items on maraxsis. Items now float away on water tiles.

Thanks for the report, its very helpful.
