### ISSUE TITLE
Trench as a surface instead of as a planet

### ISSUE THREAD

**Issue by BraveCaperCat2** [notnotmelon/maraxsis#49]
Hi! I noticed that the trench is a planet instead of a surface... so you can't launch rockets from it properly. There isn't even a space-connection between the trench and the planet so you can't even send space platforms there.

**Comment by Reflex18** [comment]
As a gameplay prospective it makes sense to make use of the unique mechanics of the mod which is the submarines to move items between the trench and the ocean. From a more logical perspective it is just really odd to launch rockets from a high pressure area that demands the use of a submarine to navigate.

**Comment by BraveCaperCat2** [comment]
Ok, so why is it a planet and not a surface?

**Comment by notnotmelon** [comment]
Surfaces are lacking many key features in the modding API compared to planets. For this reason the trench surface must be on the starmap.

**Comment by PlexPt** [comment]
Can it be hidden from the star map?

**Comment by notnotmelon** [comment]
I don't think there's a way to hide it with the current modding API.

**Comment by BraveCaperCat2** [comment]
> I don't think there's a way to hide it with the current modding API.

[Factorio Lua API](https://lua-api.factorio.com/latest/prototypes/PrototypeBase.html#hidden).
