### ISSUE TITLE
Travel to Maraxsis

### ISSUE THREAD

**Issue by YPetremann** [notnotmelon/maraxsis#5]
Due to its position, the path to go to Maraxsis would best be from nauvis.
Or if it's intended as a sort of dificulty, moving it to the other side of the star, it would still justify a path of 30 000 km

**Comment by notnotmelon** [comment]
For now, you could install this one: https://mods.factorio.com/mod/Starmap_Nexuz

**Comment by YPetremann** [comment]
I mean this as a default path
