### ISSUE TITLE
Having maraxsis active deletes constructron and constructron service station

### ISSUE THREAD

**Issue by tigartar** [notnotmelon/maraxsis#52]
I wanted to go build my trusty constructions only to find out they were missing
Checked spidertron research, nothing
Checked factorio ingame wiki, nothing

Then i remembered you joined the construction wiki the other day so decided to get rid of this mod to see if that was causing the issue and yup they came back after this mod was disabled.

I am guessing the submarine construction version is overwriting the default one or something just spitballing here tbh(at 6am)

But please can you have a look and restore them back.

**Comment by notnotmelon** [comment]
You are correct, but there's no way I can restore them. Sorry. Construction continued only supports exactly 1 prototype with a hardcoded name. So either there is construction submarines or construction spidertrons. Not both.
