### ISSUE TITLE
Placement of Pressure Dome with personal roboport causes Presure Dome to despawn

### ISSUE THREAD

**Issue by solarcloud7** [notnotmelon/maraxsis#59]
Steps to reproduce:
place a pressure dome or remove one with bots.    This also happens when you accidently place the dome in the wrong spot and a ghost item appears.

Why important:
players usually covet the first 500 glass while fighting high quality.   The thought of losing their first pressure dome can be a devastating experience.

**Comment by Andargor** [comment]
I just had the same experience, with a rare dome. Placing over solar panels, ghost got placed, and then the dome disappeared.

I think it's from the change that makes the water void all dropped items.

Could this be changed to only void items that are deposited by and inserter instead? It should avoid this kind of situation.
