### ISSUE TITLE
[issue] (i guess ?) missiing value in local file

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#64]
```
[cant-build-reason]
no-resource-for-drill=
```
i have found some value empty like this.

**Comment by notnotmelon** [comment]
Not a bug. Its needed to prevent unneeded error messages in the sand extractor.

**Comment by Fr-Dae** [comment]
so i don't need comment this one ?

```
not-operable=
cant-be-connected-to-wire=
[cant-build-reason]
no-resource-for-drill=
```

**Comment by Fr-Dae** [comment]
@notnotmelon I'm probably lacking in programming skills, but it's not a problem that no sentence is attached to it?

**Comment by notnotmelon** [comment]
Vanilla adds many error messages. For example "can't build here without resource patch".
These need to be turned off for the sand extractor to work.
Otherwise its way to confusing for the users.
