### ISSUE TITLE
mod compatibility, KSpower make diesel too.

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#65]
```
[fuel-category-name]
maraxsis-diesel=Gazoil
```

 KSpower make diesel too. it's possible to use the same for example with a kind variable `if ks power is active, then use it `

https://assets-mod.factorio.com/assets/ext/87060233a804da38f04cbbce8fb6f32d6e0c8e8c208bcff3b681865e5ff20348.png
![image](https://github.com/user-attachments/assets/f6bf6ee7-cd85-4b85-97a6-ac6e0cdc5bbe)
![Capture d’écran du 2024-12-07 16-14-43](https://github.com/user-attachments/assets/3cea7505-8dad-472f-ba38-9688948bb85a)

**Comment by notnotmelon** [comment]
This is already done.

**Comment by Fr-Dae** [comment]
maybe add some information about it on description mod ?
no issue if we have already kspower so ?

**Comment by Fr-Dae** [comment]
@notnotmelon given the missed of information, could you write here some information about kspower and its management?
or what happens when he's not around?

this message will be useful for the next person who passes through here.
