### ISSUE TITLE
[1.20.15] Multiplayer: maraxsis mod will not synchronize to clients

### ISSUE THREAD

**Issue by Andargor** [notnotmelon/maraxsis#66]
Trying to synchronize with 1.20.15 indicates constant ModMismatch on the server, entering an infinite update loop. Maraxsis does not show a release version on the synchronization popup: https://i.imgur.com/RwE8Kzy.png

Perhaps a version number is missing somewhere in the release?

**Comment by notnotmelon** [comment]
I can't really test this but I made a new update, should be fixed.

**Comment by Andargor** [comment]
> I can't really test this but I made a new update, should be fixed.

It worked, thanks.
