### ISSUE TITLE
Alien-Biomes Conflict with Volcanic-folds-underwater tile

### ISSUE THREAD

**Issue by RedDragoonSpider** [notnotmelon/maraxsis#67]
![image](https://github.com/user-attachments/assets/095e3896-0154-478c-998a-859a0836fc0c)

**Comment by d7omdev** [comment]
this issue is still present in 1.22.0
![image](https://github.com/user-attachments/assets/2a00762c-15ae-4a7a-8b5d-45ad569d0b9e)
