### ISSUE TITLE
[request]mod compatibility with informatron

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#68]
https://mods.factorio.com/mod/informatron

could you add some content for it ?

**Comment by notnotmelon** [comment]
I will not do it. I have already added lots of great info using vanilla tips and tricks. No need to duplicate the info.

![image](https://github.com/user-attachments/assets/6c9173cf-13d6-4801-aa8b-60c118e42256)

Another thing, I don't know how to use the informatron API. It would take me too much time to learn this.
