### ISSUE TITLE
Cannot automate submerging a construction sub

### ISSUE THREAD

**Issue by tylercd100** [notnotmelon/maraxsis#72]
I am not sure if this is a known bug or not, but I want to write it down for you just in case

When setting up an automated schedule with the construction subs, the submerge option does not appear to do anything.

I know you've been hard at work on this mod so I'm sure its just one of those "i'll get to it eventually" things. Keep up the good work!

**Comment by tylercd100** [comment]
Okay, upon further investigation. I guess I was just confused? I noticed that other players were able to successfully use Deisel subs to use the submerge schedule option but not construction subs.

I guess i only saw the Diesel submarine as a player only vehicle and the construction subs were the ones I was supposed to use for automation.

But since you cannot create waypoints on both surfaces without manually submerging a sub, which is not possible for the construction sub. It makes sense that construction subs are just for handling construction requests.

**Comment by notnotmelon** [comment]
Related: https://github.com/tburrows13/SpidertronPatrols/pull/9

**Comment by solarcloud7** [comment]
![image](https://github.com/user-attachments/assets/c75a5793-b2a9-4ce5-94a1-d6a2f0a014ff)
Are these instructions still correct?  Instead of left clicking,  i have to right click.

**Comment by solarcloud7** [comment]
Also subs do not like to 'submerge' when a player is in them.

**Comment by solarcloud7** [comment]
![image](https://github.com/user-attachments/assets/d3a44371-33b2-4acf-934a-18482ee73003)

**Comment by tylercd100** [comment]
@solarcloud7 I believe most of these issues will go away once the author of SpidertronPatrols merges https://github.com/tburrows13/SpidertronPatrols/pull/9

I was digging through the code and the way submerge works is by renaming the "passenger not present" train schedule (for spidertrons), so because it is using that option as a hack, the submarine wont submerge if you are riding in it.
