### ISSUE TITLE
Load start game error

### ISSUE THREAD

**Issue by vincs333** [notnotmelon/maraxsis#73]
I had version 1.15..... I had no problems. I updated the mod via the game and since then I have a message when starting the game:
Failed to load locale: missing value at _ _maraxsis_ _/locale/fr/locale.cgf: 20.

I tried version 1.20.28 to 1.20.20, downloading other previous version from factorio mod website. Every time I get the error message

**Comment by vincs333** [comment]
I modified the locale.cgf file in fr

I deleted line 4 and 5

and I deleted the word "sudo" on line 20

**Comment by notnotmelon** [comment]
This is now fixed. Thank you.

**Comment by Fr-Dae** [comment]
https://github.com/notnotmelon/maraxsis/pull/78
