### ISSUE TITLE
Impossible to mine coral. always only mines sand

### ISSUE THREAD

**Issue by hallo1126** [notnotmelon/maraxsis#88]
![grafik](https://github.com/user-attachments/assets/0aee12b8-0e22-44fb-81ea-aca54a893dbc)

**Comment by notnotmelon** [comment]
It doesn't happen for me. Can you send save?

**Comment by Fr-Dae** [comment]
It's happened to me several times with the big drills, but removing it and replacing it with a tile further away usually solves the problem.

**Comment by notnotmelon** [comment]
It's been 24 hours. I'm going to mark this as stale. Please re-raise if you have better documentation.
