### ISSUE TITLE
Submarines cannot dive

### ISSUE THREAD

**Issue by qw21zxsa** [notnotmelon/maraxsis#89]
Submarines cannot dive
![image](https://github.com/user-attachments/assets/2752cc03-9a83-477a-832b-608627b0ae60)
When I press enter according to the instructions, I will directly exit the submarine, and the submarine will not dive into the trench
![image](https://github.com/user-attachments/assets/93da2556-acce-4556-924b-0dca2eda7d55)

**Comment by lordfiSh** [comment]
You need to Press **STRG**+Enter
