### ISSUE TITLE
Submerging with a construction submarine doesn't work

### ISSUE THREAD

**Issue by lukaseder** [notnotmelon/maraxsis#94]
I first tried to submerge with a construction submarine, but this didn't work. Additionally, it disappeared (see this bug: https://github.com/notnotmelon/maraxsis/issues/93), which was very confusing. At first, I thought it submerged without me, so I was supposed to program its itinerary, but I couldn't find any such screen.

Turns out, I can hit the submerge key combination again, and it would re-appear, though not in the trench.

Here's a video illustrating the bug:
https://imgur.com/a/EYkXiQz

**Comment by notnotmelon** [comment]
Thanks for the bug report. This issue is resolved in https://github.com/notnotmelon/maraxsis/compare/e082703524b8...541eb8131672

(not yet released to the mod portal)
