### ISSUE TITLE
[issue] fps issue

### ISSUE THREAD

**Issue by Fr-Dae** [notnotmelon/maraxsis#95]
i make a platform to the pit
- paralax with "visible planet" it's not great (i guesse ? )
- if you "go to planet" your fps go to 11, and you "fall" for ever
![Capture d’écran du 2024-12-09 17-57-13](https://github.com/user-attachments/assets/57e31a61-699d-4e5f-be77-9dcb91509107)

**Comment by Fr-Dae** [comment]
> 3 minutes ago
are you a IA or something like that ?

**Comment by notnotmelon** [comment]
Haha, just a dev who wants the number of issues low as possible.
